// ======================================================
// CONFIG
// ======================================================

// Optional: alias codes she types → full address
// (e.g., in case you want to allow "HOME" instead of full street)
const LOCATION_ALIAS = {
  HOME: "123 Maple St, Springfield, IL",
  LS: "200 Lakeshore Rd, Springfield, IL",
  JACOBS: "14 Jacobs Ct, Springfield, IL",
  OFFICE: "500 Corporate Drive, Springfield, IL"
  // Add more...
};

// Mileage lookup table, generated by your batch script
// Format: "A|B": miles
const MILEAGE_TABLE = {
  "HOME|LS": 4.21,
  "LS|HOME": 4.21,
  "LS|JACOBS": 2.33,
  "JACOBS|LS": 2.33,
  "JACOBS|HOME": 5.82,
  "HOME|JACOBS": 5.82,
  // etc...
};

// Fallback if missing: geocode + directions API
const MAPBOX_TOKEN = "pk.eyJ1IjoibWF0dGhpYXN3IiwiYSI6ImNtaWc2anViaDAwZDkzY3ExZ20waml0ZnQifQ.ncDM-q4piCtrnbVIw4uexw";

// ------------------------------------------------------
// DOM elements
// ------------------------------------------------------

const inputBox = document.getElementById("locations");
const calculateBtn = document.getElementById("calculateBtn");
const statusDiv = document.getElementById("status");
const resultsDiv = document.getElementById("results");
const legsTableBody = document.querySelector("#legsTable tbody");
const totalMilesEl = document.getElementById("totalMiles");

// A new result block for daily totals
let dailyResultsDiv;

// ------------------------------------------------------
// Helpers
// ------------------------------------------------------

function setStatus(msg, isErr = false) {
  statusDiv.textContent = msg;
  statusDiv.classList.toggle("error", isErr);
}

function normalize(token) {
  return token.trim().toUpperCase().replace(/\s+/g, "");
}

function aliasToAddress(token) {
  const key = normalize(token);
  return LOCATION_ALIAS[key] || null;
}

function tableLookup(a, b) {
  const key = `${a}|${b}`;
  const rev = `${b}|${a}`;
  if (MILEAGE_TABLE[key] != null) return MILEAGE_TABLE[key];
  if (MILEAGE_TABLE[rev] != null) return MILEAGE_TABLE[rev];
  return null;
}

function metersToMiles(m) {
  return m / 1609.344;
}

function formatMiles(m) {
  return m.toFixed(2);
}

// Fallback cache for missing pairs
const fallbackCache = {}; // "A|B" → miles

// ======================================================
// Fallback API lookup (slow, only you will use this)
// ======================================================

async function geocode(address) {
  const url =
    `https://api.mapbox.com/geocoding/v5/mapbox.places/` +
    `${encodeURIComponent(address)}.json?access_token=${MAPBOX_TOKEN}&limit=1`;

  const rsp = await fetch(url);
  if (!rsp.ok) throw new Error("Geocode failed");
  const data = await rsp.json();
  if (!data.features?.length) throw new Error("No geocode match");
  const [lon, lat] = data.features[0].center;
  return { lat, lon };
}

async function routeMeters(from, to) {
  const coords = `${from.lon},${from.lat};${to.lon},${to.lat}`;
  const url =
    `https://api.mapbox.com/directions/v5/mapbox/driving/${coords}` +
    `?access_token=${MAPBOX_TOKEN}&overview=false`;

  const rsp = await fetch(url);
  if (!rsp.ok) throw new Error("Directions failed");
  const data = await rsp.json();
  if (!data.routes?.length) throw new Error("No route returned");
  return data.routes[0].distance; // meters
}

async function fallbackLookup(a, b) {
  const key = `${a}|${b}`;
  if (fallbackCache[key] != null) return fallbackCache[key];

  // Ask YOU (not her) for addresses if needed
  let addrA = aliasToAddress(a);
  let addrB = aliasToAddress(b);

  if (!addrA) addrA = prompt(`Missing address for '${a}'. Enter full address:`).trim();
  if (!addrB) addrB = prompt(`Missing address for '${b}'. Enter full address:`).trim();

  const ga = await geocode(addrA);
  const gb = await geocode(addrB);
  const meters = await routeMeters(ga, gb);
  const miles = parseFloat(formatMiles(metersToMiles(meters)));

  fallbackCache[key] = miles;
  fallbackCache[`${b}|${a}`] = miles;
  return miles;
}

// ======================================================
// Main multi-day processing
// ======================================================

async function processDailyRow(tokens) {
  let total = 0;
  let legs = [];

  for (let i = 0; i < tokens.length - 1; i++) {
    const a = normalize(tokens[i]);
    const b = normalize(tokens[i + 1]);

    let miles = tableLookup(a, b);

    if (miles == null) {
      // fallback API (rare)
      miles = await fallbackLookup(a, b);
    }

    total += miles;
    legs.push({ from: a, to: b, miles });
  }

  return { total, legs };
}

// ======================================================
// UI Handler
// ======================================================

calculateBtn.addEventListener("click", async () => {
  setStatus("Working...");
  resultsDiv.classList.add("hidden");

  // Clear old daily results
  if (dailyResultsDiv) dailyResultsDiv.remove();

  const rows = inputBox.value
    .split("\n")
    .map(r => r.trim())
    .filter(r => r.length > 0);

  if (!rows.length) {
    setStatus("Paste at least one row.", true);
    return;
  }

  // Prepare results box
  dailyResultsDiv = document.createElement("div");
  dailyResultsDiv.style.marginTop = "1rem";
  resultsDiv.insertAdjacentElement("afterend", dailyResultsDiv);

  const dailyTotals = [];

  for (const row of rows) {
    const tokens = row.split(":").map(t => t.trim()).filter(t => t.length);

    if (tokens.length < 2) {
      dailyTotals.push("0.00");
      continue;
    }

    try {
      const result = await processDailyRow(tokens);
      dailyTotals.push(formatMiles(result.total));
    } catch (err) {
      console.error(err);
      dailyTotals.push("ERROR");
    }
  }

  // Dump output column
  const column = dailyTotals.join("\n");

  dailyResultsDiv.innerHTML = `
    <h2>Daily Mileage Output</h2>
    <textarea rows="${dailyTotals.length}" style="width:100%">${column}</textarea>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">
      Copy/paste back into Excel.
    </p>
  `;

  setStatus("Done.");
});
